name: ekeel_anno_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - catalogue=2.0.10
  - certifi=2024.7.4
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.14
  - packaging=24.1
  - pathy=0.10.3
  - pip=24.0
  - pysocks=1.7.1
  - python=3.11.9
  - readline=8.2
  - requests=2.32.3
  - setuptools=69.5.1
  - spacy-legacy=3.0.12
  - spacy-model-en_core_web_sm=3.5.0
  - spacy-model-it_core_news_sm=3.5.0
  - sqlite=3.45.3
  - srsly=2.4.8
  - tbb=2021.8.0
  - tk=8.6.14
  - tqdm=4.66.4
  - urllib3=2.2.2
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==0.33.0
      - annotated-types==0.7.0
      - attrs==23.2.0
      - bcrypt==4.1.3
      - beautifulsoup4==4.12.3
      - blinker==1.8.2
      - blis==0.7.11
      - brotli==1.1.0
      - cachetools==5.3.3
      - cffi==1.16.0
      - chardet==5.2.0
      - cloudpathlib==0.18.1
      - confection==0.1.5
      - conllu==5.0.1
      - contourpy==1.2.1
      - cycler==0.12.1
      - cymem==2.0.8
      - cython==3.0.11
      - dnspython==2.6.1
      - dominate==2.9.1
      - dtw-python==1.5.1
      - email-validator==2.2.0
      - filelock==3.15.4
      - flask==2.0.3
      - flask-bootstrap==3.3.7.1
      - flask-login==0.6.3
      - flask-wtf==1.2.1
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - frozendict==2.4.4
      - fsspec==2024.6.1
      - fuzzywuzzy==0.18.0
      - gdown==5.2.0
      - gunicorn==22.0.0
      - huggingface-hub==0.23.4
      - igraph==0.11.6
      - imagehash==4.3.1
      - imageio==2.34.2
      - iso639-lang==2.2.3
      - isodate==0.6.1
      - itsdangerous==2.2.0
      - jax==0.4.30
      - jaxlib==0.4.30
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - langcodes==3.4.0
      - language-data==1.2.0
      - lazy-loader==0.4
      - levenshtein==0.25.1
      - llvmlite==0.43.0
      - lxml==5.2.2
      - marisa-trie==1.2.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - mdurl==0.1.2
      - mediapipe==0.10.14
      - ml-dtypes==0.4.0
      - more-itertools==10.4.0
      - mpmath==1.3.0
      - murmurhash==1.0.10
      - mutagen==1.47.0
      - networkx==3.3
      - nltk==3.8.1
      - numba==0.60.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu12==12.1.105
      - openai-whisper==20231117
      - opencv-contrib-python==4.10.0.84
      - opencv-python==4.10.0.84
      - opt-einsum==3.3.0
      - pafy==0.5.5
      - pandas==2.2.2
      - phrasemachine==1.0.7
      - pillow==10.4.0
      - preshed==3.0.9
      - protobuf==4.25.3
      - psutil==6.0.0
      - pycparser==2.22
      - pycryptodomex==3.20.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydub==0.25.1
      - pygments==2.18.0
      - pyld==2.0.4
      - pymongo==4.8.0
      - pyparsing==3.1.2
      - pysrt==1.1.2
      - pytesseract==0.3.10
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-levenshtein==0.25.1
      - python-rake==1.5.0
      - pytube==15.0.0
      - pytz==2024.1
      - pywavelets==1.6.0
      - pyyaml==6.0.1
      - rapidfuzz==3.9.5
      - rdflib==7.0.0
      - regex==2024.5.15
      - rich==13.7.1
      - safetensors==0.4.3
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - sentence-transformers==3.0.1
      - shellingham==1.5.4
      - six==1.16.0
      - smart-open==7.0.4
      - sounddevice==0.4.7
      - soupsieve==2.5
      - spacy==3.7.5
      - spacy-loggers==1.0.5
      - stable-ts==2.17.3
      - sympy==1.13.0
      - texttable==1.7.0
      - theano==1.0.5
      - thinc==8.2.2
      - threadpoolctl==3.5.0
      - tifffile==2024.7.24
      - tiktoken==0.7.0
      - tokenizers==0.19.1
      - torch==2.3.1
      - torchaudio==2.3.1
      - transformers==4.42.4
      - triton==2.3.1
      - typer==0.12.3
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - visitor==0.1.3
      - wasabi==1.1.3
      - weasel==0.4.1
      - websockets==12.0
      - werkzeug==2.0.3
      - wrapt==1.16.0
      - wtforms==2.3.3
      - xgboost==2.1.0
      - youtube-dl==2021.12.17
      - youtube-transcript-api==0.6.2
      - yt-dlp==2024.8.6
