name: Build and deploy mkdocs on gh-pages

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt

    - name: Clone repository
      uses: actions/checkout@v3
      with:
        repository: gaggioaxel/ekeel
        ref: main

    - name: Build site 🏗️
      run: |
        mkdocs build --clean

    - name: Deploy to GitHub Pages 🚀
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.PAGES_TOKEN }}
        publish_dir: ./ekeel
        publish_branch: gh-pages
        force_orphan: true
