name: Build and deploy mkdocs on gh-pages

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy online
      uses: actions/deploy-pages@v4