name: Build and deploy mkdocs on gh-pages

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt

    - name: Clone repository
      uses: actions/checkout@v3
      with:
        repository: gaggioaxel/ekeel
        ref: main
        # Relative path under $GITHUB_WORKSPACE to place the repository
        path: ekeel

    - name: Build site 🏗️
      run: |
        cp -r /docs/ ./
        mkdocs build

    - name: Deploy to GitHub Pages 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages
        force_orphan: true